---
title: 'Planting Trees From Private Jets: Exploring Celebrity Green Marketing'
author: "Ethan Turner"
date: "2024-03-21"
output:
  word_document: default
  pdf_document: default
---

Ethan Turner

STOR 390: Moral Machine Learning

Andrew Ackerman

March 22, 2024






**Introduction**
  The climate meltdown affects all who would prefer to leave behind an inheritable world. Whether focusing on rising sea levels or the unnaturally forced shift of agricultural calendars, the worsening situation requires a proactive approach to alleviate the descent into total climate catastrophe. Understandably, this desperate situation has incentivized a variety of so-called “green campaigns” to advertise environmental causes and raise awareness for the cataclysm that irreversible climate change will bring to Earth. As a strategy to promote these causes to the general populace, publicity campaigns frequently enlist celebrities, rather than scientific experts, to appear in green advertising. “The effectiveness of celebrities in conservation marketing”, written by Elizabeth Duthie, Diego Veríssimo, Aidan Keane, and Andrew T. Knight, examines the effectiveness of this strategy in contrast to employing qualified experts through a Bayesian experimental process. 
**Summary of Method**
  Crucially, this experiment adopts a Bayesian approach rather than a frequentist one in order to investigate the effectiveness of celebrity green campaigning. For one, the Bayesian framework allows for the input of prior distributions to diverge from the frequentist concept of testing the same null hypothesis infinitely (van de Schoot, 2013). With the input of prior knowledge, a Bayesian p-value indicates “the probability of the null hypothesis”, rather than “the probability of observing similar or more extreme data assuming that the null hypothesis is true in the population”. Rather than viewing the targeted population parameter as fixed, a Bayesian approach targets a probability distribution of a random variable, reflecting a greater uncertainty in the final results. The advantages of crafting a Bayesian model in this case include the interpretability of results when referencing the null hypothesis and natural pathway to future analysis when repurposing the resulting posterior distribution as a prior distribution for a second Bayesian model if required.
  Due to this article from Duthie et al. covering the field of marketing research, the researchers conducted a technique called “pre-testing” typical for marketing (Duthie et al., 2017). Two subdivisions comprise pre-testing: “concept testing” and “copy testing”. On this occasion, the researchers first pursued “concept testing” through semi-structured interviews (SSIs) with marketing personnel sampled using the snowball method (each interviewee was simply asked to recommend more participants) from ten different British non-governmental organizations known for activity in conservation. This gave the researchers context into how celebrities are both utilized and perceived in conservation marketing. Although not explicitly stated by the article’s authors, one would assume that the information gathered in this stage informed the setup of the copy-testing experiment at the next step.
  The researchers implemented a copy-testing experiment online to gauge audience approaches to celebrity green campaigning. Four different figures featured in four different mock advertisements: Crawford Allan as the control, the non-celebrity director of a conservation non-governmental organization (NGO), footballer David Beckham, Prince William, and celebrity naturalist Chris Packham (Duthie et al., 2017). Advertisement format was consistent across all four editions, and publicly available quotations and pictures of each figure accompanied each mock campaign. After a pilot-testing phase to ensure wording clarity, the survey containing the advertisements was distributed to hundreds of people, of which 379 responded. The null hypothesis in this case would be the lack of difference between reaction to celebrity advertisements and the non-celebrity advertisement measured via categorical data collected from the survey, leaving the alternative hypothesis postulating that there exists such a difference. 
  The recorded responses served two purposes. First, it sought to evaluate the audience’s willingness to engage (WTE) with a recorded green marketing message (Duthie et al., 2017). Secondly, it wished to evaluate the audience’s ability to recall said message. In the first “choice task”, or response process, researchers randomly assigned one of the four assignments to the participant and asked them a series of questions designed to test their willingness to engage with the advertisement and their ability to recall the information presented. Then, the survey revealed all four advertisements side-by-side and posed a series of questions and statements with which to agree or disagree, designed to both inform researchers on the participants’ perception of the celebrities and the participants’ own personal characteristics. This allowed researchers to both record respondents’ attitudes to each advertisement and more concrete characteristics such as age. 
  After filling in any missing data values from unanswered questions from participants via multiple imputation, specifically averaging ten draws with the corresponding mi package in R, the researchers introduced several models to investigate any potential findings (Duthie et al., 2017). For WTE and information recall, the organizers opted for a Bayesian cumulative logistic (logit) model. Cumulative logistic models are a brand of model generally applied to ordinal data, or data that possesses a natural order. Generally, logistic models predictively classify categorical data from a sample of a population, employed here to model the levels of enthusiasm expressed by each respondent to each advertisement. Specifically, the three categories of each response to describe WTE and recall range from “would click” to “unsure” and “would not click”, with recall responses split into “full”, “partial”, and “no” recall (Duthie et al.). 
  Bayesian models require some input of prior distributions. Although the researchers possessed no concrete pre-existing data, they opted for “weakly informative” Normal priors for cut-off points (that is, the values where classification from the model changes) of mu = 0 and sigma = 5 (Duthie et al., 2017). The fairly large variance in the prior distribution indicates a large degree of uncertainty in how the collected data will take form, as well as the classification of the priors as only “weakly informative”. Bayesian studies frequently incorporate the Normal distribution as a default prior when no clear one exists (van de Schoot, 2013). For beta parameters, researchers decided upon weakly informative Cauchy priors (location = 0, scale = 2.5) (Duthie et al.). The Cauchy distribution, developed from two independent Normal variables, is also a viable default selection due to its undefined mean and variance. The choice of two distinct varieties of prior distribution offers flexibility in modeling the two different parameters.
  For the second phase of the survey involving all four advertisements, researchers shifted to a multinomial logit model encompassing both alternative specific and individual specific predictor variables (Duthie et al., 2017). The multinomial logit model assigns membership to a group with more than two classifications. In this context, “alternative specific predictor variables” refers to “respondents’ attitudes towards each of the advertisements” and “individual specific variables” the “respondents’ explanations for their choice and their individual characteristics”. As with before, the logistical model estimates the probabilities of falling into certain classifications. Researchers introduced Cauchy priors with the same configuration as the aforementioned beta parameters for both of these types of predictor variable (Duthie et al.). 
  As is common in Bayesian models, researchers implemented Markov Chain Monte Carlo (MCMC) chains in the next step in the posterior distribution phase. The posterior distribution balances the stated prior distribution with the collected data. Via MCMC, the posterior distribution may be measured through an iterative simulation procedure. For “burn-in”, researchers ignored the first 500 Monte Carlo iterations to allow the distribution to find an equilibrium in case of a poor starting point, recording the next 2000 iterations instead (Duthie et al., 2017). With trace plots and Gelman-Rubin statistics, values not exceeding 1.01 were taken to indicate adequate convergence had been obtained, thus implying appropriate representation of the entire population. Researchers also consulted “the effective sample size and Monte Carlo Standard Error (MCSE) of each parameter as indicators of the adequacy of MCMC chain length”, or more plainly that the number of different samples from MCMC chains reached a quantity that accurately predicted the researchers’ parameters. The researchers then included results from the fitted models as odds ratios alongside 95% credible intervals. Odds ratios below 1 indicated a negative effect and odds ratios greater than 1 indicated a positive effect for each case.
**Summary of Results**
	In general, those exposed to celebrity advertisements displayed higher levels of WTE than those exposed to the control (Duthie et al., 2017). Unsurprisingly, though, respondents self-reporting that a celebrity was likely participating in the campaign to improve their own image were far less enthusiastic to engage. On the other hand, the experiment indicated that participants believing that a friend had asked the celebrity to attach their image to the green campaign, or had been paid to do so, displayed higher WTE. Looking at the profiles of each respondent, researchers noted that older people who already supported at least one conservation NGO and donated to international charities also displayed higher WTE. The fitted model 95% credible intervals, though, for apparently divided groups like college-educated females aged 55-64 living rurally (43.6% predicted to engage) and urban-living males aged 16-24 without a college education (15.3%), still intercept despite very divergent fitted model predictions. Thus, a great amount of uncertainty in the results still remains, and all following discussion only proceeds with this critical caveat.
  Despite the positive reaction to green celebrity endorsements by WTE, interestingly the study indicates a lower level of message recall in the group when exposed to celebrity messaging than to the non-celebrity control. Although largely combined as a category with WTE to this point, recall rates diverge from WTE rates both statistically and in application (Duthie et al., 2017). Higher WTE from celebrity advertisements but lower recall rates than a control suggests a disconnect between mobilization–that is, a message successfully encouraging some environmental action–and a genuinely informed public. The control, at least in this experiment, transferred its information more effectively with the cost of energizing respondents significantly less. This complicates the unquestioned adoption of celebrities in green campaigns without venturing remarkably far into normative considerations, given that the goal of green campaigning intuitively encompasses both motivation and education. Implicitly, the celebrity advertisements failed in the latter.	
Respondents were also asked to categorize their reasons for preferring certain advertisements over others when exposed to all four at once. When asked which celebrity message respondents preferred, their response was predicted by “advertisement characteristics, stated preference for a specific celebrity, and demographic characteristics” (Duthie et al., 2017). The most important advertisement features were the celebrity photograph, and then the celebrity statement. As would be expected, survey participants stating a belief that a certain celebrity “genuinely cared” regarded these advertisements more positively than they did advertisements from a celebrity they believed had been paid. 
**Normative Analysis**
  Although the experiment and resulting models indicate greater success rates of celebrities in the engagement side of green marketing, certain normative concerns remain unaddressed. Employing celebrities, whether through their own altruism or a fee, frequently strikes regular citizens as hypocritical when contrasted with the inherently wasteful celebrity lifestyle. The typical standards of running multiple large properties and traveling on private jets, aspects of the idealized celebrity lifestyle, clearly harm the environment. Further, even if private jets represent only a small portion of global emissions, celebrities bear a responsibility to live clean lives, especially when considering that their participation in green initiatives appears to carry great weight. One supposes that the upper tier of celebrities, those whose endorsements would mobilize the most people, are also statistically likely to live the most gluttonously. Even if initially persuasive, any celebrity message loses power when complemented by a story of resource wastage by an analogous societal figure.
  Assuming that a celebrity will not cease a wasteful lifestyle overnight, we must examine if a wasteful individual can somehow alleviate their negative impact by mobilizing green campaigns. Can we quantify the wastefulness of Leonardo DiCaprio, a private jet enthusiast (Worland, 2022), against his abundant climate activism? Privacy and data availability concerns quash ambitions of tracking every single celebrity, but examining the effectiveness of celebrity involvement in green marketing through both inspiring the public and effectively informing them could elucidate whether their net benefit outweighs their net harm. From a utilitarian perspective, deciding whether celebrity green campaigning is largely hypocritical or crucial to the climate fight, and under what conditions and variations of the celebrity lifestyle one or the other is true, would forge a general rule in how concerned citizens ought to view these celebrities. 
  Moving forward, we could seek an answer to the questions raised with the help of the experimentation in “The effectiveness of celebrities in conservation marketing”. However, we must likely make several assumptions. Foremost, we must claim that successfully provoking engagement in the audience, as measured here, can indeed numerically correlate with tangible environmental progress. Depending on one’s level of cynicism with green campaigning, this point is arguable but surely reasonable at some level. Through greater research into green marketing and celebrities’ true environmental benefits when involved, along with the environmental cost of an average high-profile celebrity, we may hope to quantify such celebrities’ net effect on the environment and conclude the level of hypocrisy present. 

























**Works Cited**

Duthie, E., Veríssimo, D., Keane, A., & Knight, A. T. (2017). The effectiveness of celebrities in conservation marketing. PLOS One, 12(7). https://doi.org/10.1371/journal.pone.0180027

van de Schoot, R., Kaplan, D., Denissen, J., Asendorpf, J. B., Neyer, F. J., & van Aken, M. A. G. (2013). A gentle introduction to Bayesian Analysis: Applications to Developmental Research. Child Development, 85(3), 842–860. https://doi.org/10.1111/cdev.12169

Worland, J. (2022, August 30). Why you should care about celebrities’ climate hypocrisy. Time. https://time.com/6209448/california-drought-celebrities-climate-hypocrisy/ 
